name: Build and Release Executables

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies (Tesseract & FFmpeg)
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            choco install tesseract-ocr ffmpeg --no-progress
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install tesseract ffmpeg
          else
            sudo apt-get update
            sudo apt-get install -y tesseract-ocr ffmpeg
          fi

      - name: Clean build cache
        shell: bash
        run: rm -rf build dist *.spec

      - name: Install Python Dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install moviepy==1.0.3 pyinstaller
          pip install -r requirements.txt

      - name: Install Windows-specific dependencies
        if: runner.os == 'Windows'
        run: pip install pywin32

      - name: Build with PyInstaller
        shell: bash
        run: |
          pyinstaller --name FocusSuite \
            --windowed \
            --onefile \
            --add-data "FocusSuite/about.txt:." \
            --add-data "FocusSuite/ai.txt:." \
            --hidden-import cv2 \
            --hidden-import moviepy \
            --hidden-import moviepy.editor \
            --collect-all moviepy \
            FocusSuite/main.py

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FocusSuite-${{ matrix.os }}
          path: dist/

  upload-ubuntu:
    needs: build
    if: github.event.release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
    steps:
      - name: Download Ubuntu artifact
        uses: actions/download-artifact@v4
        with:
          name: FocusSuite-ubuntu-latest
          path: ./dist

      - name: Upload Ubuntu executable as release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/FocusSuite
          asset_name: FocusSuite-linux
          asset_content_type: application/octet-stream

  upload-macos:
    needs: build
    if: github.event.release
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
    steps:
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: FocusSuite-macos-latest
          path: ./dist

      - name: Upload macOS executable as release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/FocusSuite
          asset_name: FocusSuite-macos
          asset_content_type: application/octet-stream

  upload-windows:
    needs: build
    if: github.event.release
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: FocusSuite-windows-latest
          path: ./dist

      - name: Upload Windows executable as release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/FocusSuite.exe
          asset_name: FocusSuite-win.exe
          asset_content_type: application/octet-stream
